[build]
  command = "npm ci"
  publish = "/"  # Publish directory is set to the root because index.html is in the root

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "@netlify/plugin-functions"

[functions]
  directory = "netlify/functions"  # Specify the directory where your functions are located




